ReactiveDrop/reactivedrop_public_src

src/game/server/highres_timer.cpp, src/game/server/highres_timer.h, src/game/shared/swarm/asw_gamerules.cpp
…op/reactivedrop_public_src/issues/16
=> changes to high resolution timer, fixes #16

src/game/shared/swarm/asw_player_experience.cpp
Reverts ReactiveDrop/reactivedrop_public_src#40
not working, goes wrong further below
=> Revert "quick fix for steam io error"

reactivedrop/resource/ui/hudkills.res, src/game/client/swarm/vgui/asw_hud_kills.cpp, src/game/client/swarm_sdk_client.vcxproj
Do not define USE_KILL_EVENT it was used to check counts.
=> Add hud scoreboard

reactivedrop/scripts/hudlayout.res
Sorry forgot to update hudlayout.res 
Fixes issue #75
=> Add scoreboard to hudlayout.res

src/game/shared/swarm/asw_marine_gamemovement.cpp
fixes a nullptr exception that crashes servers randomly, crashdumps are available if required.
=> fix a nullptr exception in game movement

src/game/client/swarm/c_asw_player.cpp, src/game/shared/swarm/asw_gamerules.cpp
Let the server control marine avoidance
=> Make asw_player_avoidance a server-side replicate cvar

src/game/client/hud_basechat.cpp
In a later commit I also removed that function call.
=> Fix comment, remove call to MoveToFront()

contentsrc/mapsrc/rd-res2research7.vmf
Thanks to @Deerlord0 for report.
=> Fixed missing english string

src/game/client/swarm/gameui/swarm/vfoundpublicgames.cpp, src/game/shared/swarm/asw_gamerules.cpp
This needs to be tested. Issue #147
=> Filter dedicated servers from lobby list.

src/game/shared/swarm/rd_release_flags.h
=> Disable pre-release campaigns

src/game/server/vscript_server.cpp
- Add global script function to spawn an entity and set its KeyValues from a passed table.
`CBaseEntity SpawnEntityFromTable( string name, table )` //Spawn entity from KeyValues in table - 'name' is entity name, rest are KeyValues for spawn.
=> Add SpawnEntityFromTable Function

src/game/server/swarm/asw_door.cpp
fix the bug of doors staying up when they were killed with dent amount none
=> fix ghost doors

src/game/server/vscript_server.cpp
- Add new VScript class **TempEnts** which allows creating Temporary Entities on clients.
- Add new global VScript functions to use when creating Temporary Entities.
**TempEnts**
_Queue a temp entity for transmission on a client from a passed table of SendProp data.
Passing null for a player will playback Temp Entity on all clients._
`void Create( CBasePlayer player, string name, float delay, table )`
_Fills in a passed table with all SendProps and their types for the temp entity_
`void GetPropTypes( string name, table )`
_Fills in a passed table with the names of all temp entities_
`void GetNames( table )`
**Global**
_Precaches a particle material_
`int PrecacheParticleSystem( string name )`
_Converts a previously precached material into an index_
`int GetParticleSystemIndex( string name …
=> Add ScriptTempEnts Class and Functions

contentsrc/mapsrc/rd-res3miningcamp.vmf
by setting npc_bullseye faction to marines
=> para5 & res3: prevent bots attacking npc_bullseye

src/game/client/c_baseplayer.cpp, src/game/client/c_baseplayer.h, src/game/client/c_playerresource.cpp
This will avoid privacy issue as well.
=> Lobby player info to match dedicated server.

reactivedrop/resource/ui/basemodui/gamesettings.res, src/game/client/swarm/gameui/swarm/vadvancedsettings.cpp
**Advanced Settings**
- Fix UI navigation so all buttons can be selected when using a controller or arrow keys.
**Game Settings**
- Fix UI navigation so you can navigate to the bottom setting from the Campaign button.
=> UI Nav Fixes

src/game/server/vscript_server.cpp
- Add new VScript class and functions to allow dispatching usermessages on clients.
**UserMessages**
Returns a new usermessage instance
`CScriptUserMessage Begin( CBasePlayer hPlayer, string messageName )`
Returns -1 if not found, otherwise, returns appropriate index
`int LookupUserMessage( string name )`
Returns the size of the usermessage
`int GetUserMessageSize( int index )`
Returns the name of the usermessage
`string GetUserMessageName( int index )`
Returns true if the usermessage index is valid
`bool IsValidIndex( int index )`
Returns number of registered user messages.
`int Count()`
**CScriptUserMessage**
Returns the name of this usermessage
`string GetMessageName()`
Store integer data for write operation
`void WriteInt( int value, int type )`
Store float data for write operation …
=> Add New UserMessages VScript Class

src/game/client/swarm/gameui/swarm/vadvancedsettings.cpp, src/game/client/swarm/gameui/swarm/vadvancedsettings.h
- Add a workaround to fix not being able to navigate Flyout menus with keyboard/controller for Advanced Settings dropdowns.
=> Fix Advanced Settings Navigation

src/game/server/swarm/asw_campaign_save.cpp, src/game/shared/swarm/asw_gamerules.cpp
=> [needs-testing] do not save the game (to disk) on marine death or revive.

src/game/client/c_playerresource.cpp, src/game/client/c_playerresource.h, src/game/client/swarm/vgui/playerlistline.cpp
wasnt able to reproduce it. hopefully when the bug happens then pVoiceMgr->IsPlayerBlocked returns false, then it throws a warning in the console and tries muting the player again
=> possible fix for voice manager randomly unmuting

src/game/shared/swarm/asw_marine_shared.cpp
=> if there is no meelee attack, set zero

src/game/shared/swarm/asw_marine_shared.cpp
Changed default according to #352
=> change default for meelee damage

contentsrc/mapsrc/rd-bonus_mission2.vmf, contentsrc/mapsrc/rd-bonus_mission3.vmf, contentsrc/mapsrc/rd-bonus_mission4.vmf
=> add briefing cameras to bonus missions

contentsrc/mapsrc/ASI-Jac2-Deima.vmf
I got stuck on bridge with bloodhound and we couldn't progress so I looked into it.
I believe it was caused by a marine skipping past the trigger.
I extended the trigger across the whole edge of the bridge so it should trigger each time. The reset trigger delay was dropped to 0.1 from 1.0 just in case that was also a factor.
=> Deima Bug Fix

src/game/server/swarm/asw_marine_resource.cpp
Remove duplicate field definition for m_MarineProfileIndex
=> asw_marine_resource.cpp duplicate field definition

src/game/shared/gamemovement.cpp, src/game/shared/swarm/asw_gamerules.cpp, src/game/shared/swarm/asw_marine_gamemovement.cpp
=> fix nullptr in game movement

src/game/client/viewrender.cpp
Possible cause of https://partner.steamgames.com/errors/errorid/12545658
=> safeguard entity render

contentsrc/mapsrc/rd-par1unexpected_encounter.vmf, contentsrc/mapsrc/rd-par2hostile_places.vmf
reference: https://youtu.be/iePfZEW_x-E
also on the nolight ceilings
=> paranoia 1&2: patch up holes in geometry

src/game/client/particles_new.cpp
Possible crash in particles when using multiple threads
https://partner.steamgames.com/errors/errorid/14879711
=> particle crash

src/game/client/swarm/c_asw_marine.cpp, src/game/client/swarm/c_asw_marine.h, src/game/server/swarm/asw_marine.cpp, src/game/server/swarm/asw_marine.h, src/game/shared/swarm/asw_marine_gamemovement.cpp, src/game/shared/swarm/asw_melee_system.cpp
// Send true to make marine roll, send false to make marine jump 
void SetMarineRolls( bool bRolls )
=> make it possible to change marine rolls individually for each marine

contentsrc/mapsrc/rd-lan2_sewer.vmf, reactivedrop/fgd/swarm.fgd, src/game/server/swarm/asw_barrel_radioactive.cpp, src/game/server/swarm/asw_barrel_radioactive.h
+ added OnBurst output to gas barrels
=> lana2: make gas barrels do 10000 damage to shamans

reactivedrop/fgd/swarm.fgd, src/game/client/swarm/c_asw_button_area.cpp, src/game/client/swarm/c_asw_button_area.h, src/game/server/swarm/asw_button_area.cpp, src/game/server/swarm/asw_button_area.h
use panel message,
need tech message,
exit panel message,
hack panel message
=> make it possible to customize button area icon texts, see #437

src/game/server/hl2/npc_zombine.cpp, src/game/server/hl2/npc_zombine.h, src/game/server/swarm/asw_inhabitable_npc.cpp, src/game/server/swarm/asw_inhabitable_npc.h, src/game/server/swarm/asw_marine.cpp, src/game/server/swarm/asw_marine.h, src/game/server/swarm_sdk_server.vcxproj
todo - make the marine not gib and have no clientsided ragdoll when a zombine spawns from his death
=> add zombine spawn from marine death logic

src/game/server/swarm/asw_computer_area.cpp
currently we cant make a hack be fast from altering hacking scale because how big of an impact download time has, which is not good, so make hacking scale speed up the download too
=> simple hacking: hacking scale speeds up download

src/game/shared/swarm/rd_workshop.cpp
=> add option to specify steam ugc query cache duration

contentsrc/mapsrc/rd-ocs3uscmedusa.vmf
https://steamcommunity.com/app/563560/discussions/2/3820780968134412906/
ocs3:
made aliens not spawn under the second elevator
made aliens and marines die when the first elevator crushes them
jac7:
made invisible harvesters not inflict damage
=> ocs3 and jac7 map fixes

reactivedrop/resource/alien_selection_asbi.txt
me and dmitriy didnt like that, i think more people wont like that also
=> remove antlionguards from asbi

reactivedrop/resource/rd_advanced_settings.txt, src/game/client/swarm/vgui/asw_hud_3dmarinenames.cpp
=> fix draw player label

src/game/client/bone_merge_cache.cpp, src/game/client/c_env_projectedtexture.cpp, src/game/client/clientshadowmgr.cpp, src/game/client/hud_basechat.cpp, src/game/client/menu.cpp, src/game/client/swarm/gameui/swarm/basemodpanel.cpp, src/game/client/swarm/gameui/swarm/rd_workshop_frame.cpp, src/game/client/swarm/gameui/swarm/vflyoutmenu.cpp, src/game/client/swarm/gameui/swarm/vgamesettings.cpp, src/game/client/swarm/gameui/swarm/vloadingprogress.cpp, src/game/client/swarm/gameui/swarm/vtransitionscreen.cpp, src/game/client/swarm/vgui/asw_hud_use_icon.cpp, src/game/client/viewrender.cpp, src/game/client/viewrender.h, src/game/missionchooser/VMFExporter.cpp, src/game/missionchooser/asw_map_builder.cpp, src/game/server/ai_basenpc.cpp, src/game/server/client.cpp, src/game/server/point_devshot_camera.cpp, src/game/shared/weapon_parse.cpp
=> Additional pedantry
