src/public/tier0/memoverride.cpp

fixes: 
```
C:\Users\<username>\Projects\private\reactivedrop_public_src\src\public\tier0\memoverride.cpp(252,8): error C2382: '_msize_base': redefinition; different exception specifications
C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt\corecrt_malloc.h(107): message : see declaration of '_msize_base'
```
this fixes it locally, please verify this before merge.

fix declaration of memoverride.cpp mismatching 

---

src/game/shared/swarm/asw_player_experience.cpp

This fixes:
```CASW_Player: Server failed to download stats from Steam, IO error```
As far as I can see, Steam callbacks don't seem to have a bIOError parameter? Commenting this out fixes some things for now, but this might need further investigation.
`pUserStatsReceived->m_eResult`  seems to have the correct response code further down the method.

quick fix for steam io error

---

src/game/shared/swarm/rd_challenges_shared.cpp

When selecting challenge from the mission chooser prior to creating a game it will crash game.

Fix challenge selection

---

src/game/server/baseentity.cpp

Static prop is part of the world entity to avoid crashing the game when using command

Avoid removing world entity

---

src/game/client/swarm/clientmode_asw.cpp

Keeps leader from having to keep clicking restart mission on server that don't have auto restart turned on.

Add convar cl_auto_restart_mission

---

.github/workflows/build.yaml

Enable automated building of reactivedrop_public branch and pull requests on it. 
This makes checking if the build succeeds easier. We can add quality tests, like formatting checks easily in future.
_(setup should be correct, but can only test this after merge)_

enable automated building

---

src/game/missionchooser/asw_mission_chooser_source_local.cpp

Set minimum valve for asw_max_saves to `2`. If lower, crashes or lockups may occur. Fixes #181

set minimum on asw_max_saves

---

src/game/shared/swarm/asw_player_experience.cpp

This call seems to always `bIOError`. Move it from warning() to devWarning() to limit logspam for now.
Affects #149

Steam IO Error

---

src/game/server/baseentity.cpp
src/game/server/baseentity.h
src/game/server/vscript_server.cpp

Update CBaseEntity::ScriptPrecacheModel to return the model index and add two new script functions.
**Global**
int PrecacheModel( string modelName ) // Precache a model after the map has loaded and return index of the model
int GetModelIndex( string modelName ) // Returns index of model by name

Update VScript Functions

---

src/game/shared/swarm/asw_gamerules.cpp

If the map is not official or in the workshop, the mission display title is empty.

Add map name to lobby data.

---

src/game/server/vscript_server.cpp

- Add the PlayerVoiceListener class to VScript with access to the following functions.
**PlayerVoiceListener**
Returns whether the player specified is speaking.
`bool IsPlayerSpeaking( int nPlayerIndex )`
Returns the number of seconds the player has been continuously speaking.
`float GetPlayerSpeechDuration( int nPlayerIndex )`

Expose CPlayerVoiceListener for VScript

---

src/game/server/swarm/asw_player.cpp
src/game/server/swarm/asw_player.h

- Add new VScript functions for CASW_Player.
Returns entity the player is inhabiting
`CBaseEntity GetNPC()`
Returns entity the player is spectating
`CBaseEntity GetSpectatingNPC()`
Returns entity the player is spectating, else will return inhabiting entity
`CBaseEntity GetViewNPC()`
Returns the marine the player is commanding
`CASW_Marine GetMarine()`
Finds the nearest entity in front of the player
`CBaseEntity FindPickerEntity()`
Returns the world location directly beneath the player's crosshair
`Vector GetCrosshairTracePos()`

Add New CASW_Player VScript Functions

---

src/game/client/hud_basechat.cpp
src/game/client/hud_basechat.h
src/game/client/swarm/vgui/asw_hud_chat.cpp
src/game/server/vscript_server.cpp

Uses color character with 3 additional ascii characters in range of 0x20 to 0x7E to output RGB values to the client text.
Example:
ClientPrint(null, 3, "\x08~!!RED\x08~A!ORANGE\x08~~!YELLOW\x08!~!GREEN\x08!~~AQUA\x08!A~LIGHT_BLUE\x08!!~BLUE\x08~A`PINK\x08~a~PINK");
This is further simplified by the TextColor vscript function that accepts RGB and outputs the closest ascii range.
Example:
ClientPrint(null, 3, TextColor(255, 0 0) +"RED" + " " + TextColor(163, 73, 164)+ "PURPLE" + " " + TextColor(255, 255, 255)+ "WHITE" + " " + TextColor(0, 0, 0)+ "BLACK" + " " + TextColor(155, 155, 155)+ "SILVER");

Adds support for RGB colored text for chat

---

src/game/server/swarm/asw_harvester.cpp

after the previous commit realised that it would be very inconsistent a.k.a hard to predict because it could lead to situations where xenomytes wouldn't be released when the nade hit was not direct
optimal but not a clean way to check if it was a direct nade hit ( info.GetDamage() > 135.0f ) ensures that the explosion which killed the harvesters was a direct nade hit, moree consistent behaviour
+a convar to make xenomytes always be released if some challenges wanna use it to make it a bit harder

HARVESTER: closer to previous behaviour + a convar

---

contentsrc/mapsrc/rd-bio1operationx5.vmf
contentsrc/mapsrc/rd-res4mines.vmf
contentsrc/mapsrc/rd-tft2AbandonedMaintenance.vmf
contentsrc/mapsrc/rd-til6YanaurusMine.vmf
contentsrc/mapsrc/rd-til7Factory.vmf

317 - nh2 techreq bug
289 - bio3 nadeable invisible ceiling
274 - tft2 nadeable invisible ceiling
270 - visuals - til7 invisible walls
269 - visuals - til6 invisible walls
255 - res4 obj markers
249 - bio1 fix vent holes only do damage for 2.8 seconds (+ prevent prespawn spawning in the elevator at the end and blocking it) 
62 - nh3 countdown cancels early
61 - jac7 safespot
fixes #317
fixes #289
fixes #274
fixes #270
fixes #269
fixes #255
fixes #249
fixes #62
fixes #61

various map bugfixes again

---

reactivedrop/resource/swarmopedia.txt
src/game/shared/swarm/asw_weapon_flamer_shared.cpp
src/game/shared/swarm/asw_weapon_flamer_shared.h

Based on community feedback in https://steamcommunity.com/app/563560/discussions/2/3361397532258307150/, the flamer should not be made heavy for now, with one of the reasons, it is a useful asset in speed runs.
This reverts commit b7428a52012b8deda7302ba62e55b95fd1be71a0, reversing changes made to 52c7a5fdde58b19a0308ac1efa128c95f21e2eb0.

Revert "Merge pull request #309 from BenLubar/flamer-heavy"

---

src/game/client/swarm/gameui/swarm/vfoundpublicgames.cpp

This changes the default made in https://github.com/ReactiveDrop/reactivedrop_public_src/pull/146.
Reason: new players expect to find games when they search for lobbies. Right now, games on dedicated servers are not shown.
Regarding the concerns, raised in the comments. I just tested, if I can view the client IP's on hosted lobbies:
```
$> conntrack -L | grep udp | grep 85.145.xxx.xxx
// 85.145.xxx.xxx = client
// 85.214.xxx.xxx = server
// dump is done on the firewall in front of the server
conntrack v1.4.6 (conntrack-tools): 96 flow entries have been shown.
udp      17 299 src=85.145.xxx.xxx dst=85.214.xxx.xxx sport=56402 dport=33857 src=85.214.xxx.xxx dst=85.145.xxx.xxx sport=33857 dport=56402 [ASSURED] mark=0 use=1
```
The result, as expected, the client IP just shows in the …

do not filter dedicated servers by default

---

src/game/shared/igamesystem.cpp

sys::init() can appearently be not set on some Windows 8.0 systems. Just set `valid` to `false` to skip it, and continue to the next in the loop. Hopefully fixes crash #14775431

sys can be empty on older windows systems

---

src/game/server/swarm/rd_briefing_camera.cpp
src/game/server/swarm/rd_briefing_camera.h

this is what happens when only documentation is comments in the source code. end up testing things for hours with nothing working and one evening after a couple months suddently find a flag in other classes with a comment that says this is why its been not working

fix briefing camera not transmitting with a parent

---

src/game/shared/swarm/asw_weapon_laser_mines.cpp
src/game/shared/swarm/asw_weapon_laser_mines.h

this prediction happens a little earlier than the actual throw, so there will be occassional cases when the animation does play when it shouldnt have or it will not play when it should have. though still better than always playing imo.

lasermines: add a prediction whether to play a throwing animation

---

utils/build_maps.py

replaced a lot of asw_drone_jumper spawners with normal asw_drone, it looks like pathfinding calculations are heavy with asw_drone_jumper because the map's nodegraph for them is connected from the place they spawn (below the bridge in snowy area or near the door) all the way to the spawn, and with normal asw_drone the nodegraph is isolated into two pieces before the fall and after the fall, just like for marines.
Also the nodegraph itself was unnecesarily complex, removed half of the nodes. cut down nodegraph build time from 20 seconds to 10 seconds.
All in all the map should be a bit easier not just in terms of lack of lag but i think its worth it

lana1: optimizations
